# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ParamUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Param(object):
    def setupUi(self, Param):
        Param.setObjectName("Param")
        Param.resize(600, 400)
        self.gridLayout = QtWidgets.QGridLayout(Param)
        self.gridLayout.setObjectName("gridLayout")
        self.ParamGbox = QtWidgets.QGroupBox(Param)
        self.ParamGbox.setTitle("")
        self.ParamGbox.setObjectName("ParamGbox")
        self.SubLayout = QtWidgets.QGridLayout(self.ParamGbox)
        self.SubLayout.setObjectName("SubLayout")
        self.gridLayout.addWidget(self.ParamGbox, 1, 0, 1, 1)

        self.retranslateUi(Param)
        QtCore.QMetaObject.connectSlotsByName(Param)

    def retranslateUi(self, Param):
        _translate = QtCore.QCoreApplication.translate
        Param.setWindowTitle(_translate("Param", "Form"))
