# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ParamMate_Tools_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParamMateUI(object):
    def setupUi(self, ParamMateUI):
        ParamMateUI.setObjectName("ParamMateUI")
        ParamMateUI.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(ParamMateUI)
        self.centralwidget.setObjectName("centralwidget")
        self.MainLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.MainLayout.setObjectName("MainLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.SubWidgetLayout = QtWidgets.QGridLayout(self.groupBox)
        self.SubWidgetLayout.setObjectName("SubWidgetLayout")
        self.MainLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        ParamMateUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ParamMateUI)
        self.statusbar.setObjectName("statusbar")
        ParamMateUI.setStatusBar(self.statusbar)

        self.retranslateUi(ParamMateUI)
        QtCore.QMetaObject.connectSlotsByName(ParamMateUI)

    def retranslateUi(self, ParamMateUI):
        _translate = QtCore.QCoreApplication.translate
        ParamMateUI.setWindowTitle(_translate("ParamMateUI", "ParamMate_Tools"))
        self.groupBox.setTitle(_translate("ParamMateUI", "Window"))
