# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SerialToolUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SerialTool(object):
    def setupUi(self, SerialTool):
        SerialTool.setObjectName("SerialTool")
        SerialTool.resize(200, 800)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SerialTool)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ConfigureGbox = QtWidgets.QGroupBox(SerialTool)
        self.ConfigureGbox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ConfigureGbox.setObjectName("ConfigureGbox")
        self.ConfigureGboxLayout = QtWidgets.QGridLayout(self.ConfigureGbox)
        self.ConfigureGboxLayout.setVerticalSpacing(20)
        self.ConfigureGboxLayout.setObjectName("ConfigureGboxLayout")
        self.BaudLab = QtWidgets.QLabel(self.ConfigureGbox)
        self.BaudLab.setObjectName("BaudLab")
        self.ConfigureGboxLayout.addWidget(self.BaudLab, 1, 0, 1, 1)
        self.DatabitLab = QtWidgets.QLabel(self.ConfigureGbox)
        self.DatabitLab.setObjectName("DatabitLab")
        self.ConfigureGboxLayout.addWidget(self.DatabitLab, 2, 0, 1, 1)
        self.DataBitCbox = QtWidgets.QComboBox(self.ConfigureGbox)
        self.DataBitCbox.setObjectName("DataBitCbox")
        self.ConfigureGboxLayout.addWidget(self.DataBitCbox, 2, 1, 1, 1)
        self.CheckBitCbox = QtWidgets.QComboBox(self.ConfigureGbox)
        self.CheckBitCbox.setObjectName("CheckBitCbox")
        self.ConfigureGboxLayout.addWidget(self.CheckBitCbox, 3, 1, 1, 1)
        self.PortLab = QtWidgets.QLabel(self.ConfigureGbox)
        self.PortLab.setObjectName("PortLab")
        self.ConfigureGboxLayout.addWidget(self.PortLab, 0, 0, 1, 1)
        self.StopBitLab = QtWidgets.QLabel(self.ConfigureGbox)
        self.StopBitLab.setObjectName("StopBitLab")
        self.ConfigureGboxLayout.addWidget(self.StopBitLab, 4, 0, 1, 1)
        self.CheckBitLab = QtWidgets.QLabel(self.ConfigureGbox)
        self.CheckBitLab.setObjectName("CheckBitLab")
        self.ConfigureGboxLayout.addWidget(self.CheckBitLab, 3, 0, 1, 1)
        self.PortCbox = QtWidgets.QComboBox(self.ConfigureGbox)
        self.PortCbox.setObjectName("PortCbox")
        self.ConfigureGboxLayout.addWidget(self.PortCbox, 0, 1, 1, 1)
        self.RefreshPbtn = QtWidgets.QPushButton(self.ConfigureGbox)
        self.RefreshPbtn.setObjectName("RefreshPbtn")
        self.ConfigureGboxLayout.addWidget(self.RefreshPbtn, 5, 0, 1, 1)
        self.PortSwitchPbtn = QtWidgets.QPushButton(self.ConfigureGbox)
        self.PortSwitchPbtn.setObjectName("PortSwitchPbtn")
        self.ConfigureGboxLayout.addWidget(self.PortSwitchPbtn, 5, 1, 1, 1)
        self.BaudCbox = QtWidgets.QComboBox(self.ConfigureGbox)
        self.BaudCbox.setObjectName("BaudCbox")
        self.ConfigureGboxLayout.addWidget(self.BaudCbox, 1, 1, 1, 1)
        self.StopBitCbox = QtWidgets.QComboBox(self.ConfigureGbox)
        self.StopBitCbox.setObjectName("StopBitCbox")
        self.ConfigureGboxLayout.addWidget(self.StopBitCbox, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ConfigureGboxLayout.addItem(spacerItem, 6, 0, 1, 2)
        self.horizontalLayout.addWidget(self.ConfigureGbox)

        self.retranslateUi(SerialTool)
        QtCore.QMetaObject.connectSlotsByName(SerialTool)

    def retranslateUi(self, SerialTool):
        _translate = QtCore.QCoreApplication.translate
        SerialTool.setWindowTitle(_translate("SerialTool", "Form"))
        self.ConfigureGbox.setTitle(_translate("SerialTool", "配串口置"))
        self.BaudLab.setText(_translate("SerialTool", "波特率："))
        self.DatabitLab.setText(_translate("SerialTool", "数据位："))
        self.PortLab.setText(_translate("SerialTool", "端口："))
        self.StopBitLab.setText(_translate("SerialTool", "停止位："))
        self.CheckBitLab.setText(_translate("SerialTool", "校验位："))
        self.RefreshPbtn.setText(_translate("SerialTool", "刷新串口"))
        self.PortSwitchPbtn.setText(_translate("SerialTool", "打开串口"))
