# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WaveformWidgetUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_From(object):
    def setupUi(self, From):
        From.setObjectName("From")
        From.resize(800, 600)
        self.gridLayout_2 = QtWidgets.QGridLayout(From)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(From)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.XaxisZoomPbtn = QtWidgets.QPushButton(self.groupBox)
        self.XaxisZoomPbtn.setObjectName("XaxisZoomPbtn")
        self.gridLayout.addWidget(self.XaxisZoomPbtn, 2, 3, 1, 1)
        self.SwitchAdaptivePbtn = QtWidgets.QPushButton(self.groupBox)
        self.SwitchAdaptivePbtn.setObjectName("SwitchAdaptivePbtn")
        self.gridLayout.addWidget(self.SwitchAdaptivePbtn, 2, 5, 1, 1)
        self.graphicsView = QChartView(self.groupBox)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 1, 6)
        self.IDLab = QtWidgets.QLabel(self.groupBox)
        self.IDLab.setObjectName("IDLab")
        self.gridLayout.addWidget(self.IDLab, 0, 0, 1, 1)
        self.YaxisZoomPbtn = QtWidgets.QPushButton(self.groupBox)
        self.YaxisZoomPbtn.setObjectName("YaxisZoomPbtn")
        self.gridLayout.addWidget(self.YaxisZoomPbtn, 2, 0, 1, 1)
        self.XaxisShrinkPbtn = QtWidgets.QPushButton(self.groupBox)
        self.XaxisShrinkPbtn.setObjectName("XaxisShrinkPbtn")
        self.gridLayout.addWidget(self.XaxisShrinkPbtn, 2, 4, 1, 1)
        self.YaxisShrinkPbtn = QtWidgets.QPushButton(self.groupBox)
        self.YaxisShrinkPbtn.setObjectName("YaxisShrinkPbtn")
        self.gridLayout.addWidget(self.YaxisShrinkPbtn, 2, 1, 1, 1)
        self.YaxisZeroPbtn = QtWidgets.QPushButton(self.groupBox)
        self.YaxisZeroPbtn.setObjectName("YaxisZeroPbtn")
        self.gridLayout.addWidget(self.YaxisZeroPbtn, 2, 2, 1, 1)
        self.ChannelsLab = QtWidgets.QLabel(self.groupBox)
        self.ChannelsLab.setObjectName("ChannelsLab")
        self.gridLayout.addWidget(self.ChannelsLab, 0, 1, 1, 1)
        self.DataTypeLab = QtWidgets.QLabel(self.groupBox)
        self.DataTypeLab.setObjectName("DataTypeLab")
        self.gridLayout.addWidget(self.DataTypeLab, 0, 4, 1, 2)
        self.SeriesTypeLab = QtWidgets.QLabel(self.groupBox)
        self.SeriesTypeLab.setObjectName("SeriesTypeLab")
        self.gridLayout.addWidget(self.SeriesTypeLab, 0, 2, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(From)
        QtCore.QMetaObject.connectSlotsByName(From)

    def retranslateUi(self, From):
        _translate = QtCore.QCoreApplication.translate
        From.setWindowTitle(_translate("From", "Form"))
        self.XaxisZoomPbtn.setText(_translate("From", "X轴放大"))
        self.SwitchAdaptivePbtn.setText(_translate("From", "开启自适应"))
        self.IDLab.setText(_translate("From", "ID："))
        self.YaxisZoomPbtn.setText(_translate("From", "Y轴放大"))
        self.XaxisShrinkPbtn.setText(_translate("From", "X轴缩小"))
        self.YaxisShrinkPbtn.setText(_translate("From", "Y轴缩小"))
        self.YaxisZeroPbtn.setText(_translate("From", "Y轴归0"))
        self.ChannelsLab.setText(_translate("From", "通道数："))
        self.DataTypeLab.setText(_translate("From", "数据类型："))
        self.SeriesTypeLab.setText(_translate("From", "控件类型："))
from PyQt5.QtChart import QChartView
