#!/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@File    :   Param.py    
@Contact :   15663678208
@Modify Time      @Author    @Version    @Desciption
------------      -------    --------    -----------
2022/8/8 8:57   LHD      1.0         None
"""

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ParamUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QWidget, QGroupBox

# 数据类型列表
DataTypeStrList = ('uint8', 'uint16', 'uint32', 'uint64', 'int8', 'int16', 'int32', 'int64', 'float', 'double')


class ParamSubClass(QWidget):
    def __init__(self, Name='', DataType=0):
        super(ParamSubClass, self).__init__()
        self.NameLab = QtWidgets.QLabel()
        self.NameLab.setAlignment(Qt.AlignRight)
        self.NameLab.setAlignment(Qt.AlignCenter)
        self.NameLab.setText(Name + '：')
        if DataType < 8:  # 整数类型
            self.DataSBox = QtWidgets.QSpinBox()
        elif 8 <= DataType < 10:
            self.DataSBox = QtWidgets.QDoubleSpinBox()
        self.setupUi()

    def setupUi(self):
        Layout = QtWidgets.QHBoxLayout()
        Layout.addWidget(self.NameLab)
        Layout.addWidget(self.DataSBox)
        self.setLayout(Layout)


class MyParam(QGroupBox):
    ID: int
    ParamSubList: list

    def __init__(self, ID=0, Name=''):
        super(MyParam, self).__init__()
        self.ID = ID
        self.ParamSubList = []
        self.setupUi()
        self.setTitle(Name)

    def setupUi(self):
        self.setObjectName("Param")
        self.resize(600, 400)
        self.setObjectName("ParamGbox")
        self.SubLayout = QtWidgets.QGridLayout(self)
        self.SubLayout.setObjectName("SubLayout")

    def AddChannels(self, Name='', DataType=0):
        ParamSubNum = len(self.ParamSubList)
        ParamSub = ParamSubClass(Name=Name, DataType=DataType)
        row = ParamSubNum >> 0x03  # 获取控件所在行
        col = ParamSubNum & 0x07  # 获取控件所在列
        self.SubLayout.addWidget(ParamSub, row, col, 1, 1)
        self.ParamSubList.append(ParamSub)


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    ui = MyParam(Name='test')
    ui.show()
    sys.exit(app.exec_())
